[build]
  command = "mise install && gem install bundler && bundle install && bundle exec rails assets:precompile"
  publish = "public"

[build.environment]
  MISE_ROOT = "/opt/buildhome/.mise"
  MISE_USE_TOML = "false"

[[plugins]]
  package = "netlify-plugin-mise"
